MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window8_512
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: assets/ckpt/epoch_100th.pth
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 8